name: Generate GitHub Stats
permissions:
  contents: write  # Grant write permission to the repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to v3


      - name: Generate GitHub Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=amalakkad93&count_private=true&include_all_commits=true&show_icons=true&hide_border=true&title_color=22c55e&icon_color=22c55e&text_color=7f7f7f&bg_color=00000000&token=${{ secrets.GH_STATS_TOKEN }}"
          curl -o languages.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=amalakkad93&hide_border=true&border_radius=6&langs_count=20&layout=pie&theme=shadow_green&bg_color=00000000&text_color=7f7f7f&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add stats.svg languages.svg
          git commit -m "Update GitHub stats"
          git push
